##
# Site settings
##
lang: "en"
author: "Eric Paul"
title: "Eric Paul"
description: "Eric P site description"
keywords: "multipurposegeek, mpgeek, portland web developer, portland technology consultant"
email: multipurposegeek@gmail.com
email_display: "multipurposegeek (at) gmail.com"
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username: mpgeek
github_username: mpgeek

# Dependencies
plugins:
  - jekyll-sitemap

# Build settings
markdown: kramdown
exclude: [scripts]

# Build dir
destination: _build/html


# SASS
sass:
  sass_dir: _sass
  style: :compressed
